--------------------------------------------------------
--  File created - Friday-October-19-2018   
--------------------------------------------------------
DROP SEQUENCE "MOOLLS"."CHAT_EVENT_SEQ";
DROP SEQUENCE "MOOLLS"."CHAT_USER_SEQ";
DROP TABLE "MOOLLS"."CHAT_EVENT" cascade constraints;
DROP TABLE "MOOLLS"."CHAT_EVENT_TYPE" cascade constraints;
DROP TABLE "MOOLLS"."CHAT_USER" cascade constraints;
DROP TABLE "MOOLLS"."CHAT_USER_ROLE" cascade constraints;
DROP TABLE "MOOLLS"."CHAT_USER_STATUS" cascade constraints;
--------------------------------------------------------
--  DDL for Sequence CHAT_EVENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MOOLLS"."CHAT_EVENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CHAT_USER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MOOLLS"."CHAT_USER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table CHAT_EVENT
--------------------------------------------------------

  CREATE TABLE "MOOLLS"."CHAT_EVENT" 
   (	"EVENT_ID" NUMBER, 
	"EVENT_TYPE" NUMBER, 
	"FROM_USER" NUMBER, 
	"TO_USER" NUMBER, 
	"MESSAGE" VARCHAR2(250 BYTE) DEFAULT NULL, 
	"IP" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"TIMESTAMP" TIMESTAMP (6) DEFAULT current_timestamp
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHAT_EVENT_TYPE
--------------------------------------------------------

  CREATE TABLE "MOOLLS"."CHAT_EVENT_TYPE" 
   (	"EVENT_TYPE_ID" NUMBER, 
	"EVENT_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHAT_USER
--------------------------------------------------------

  CREATE TABLE "MOOLLS"."CHAT_USER" 
   (	"USER_ID" NUMBER, 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"MD5_PASS" VARCHAR2(50 BYTE), 
	"REG_TIMESTAMP" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"STATUS" NUMBER, 
	"ROLE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHAT_USER_ROLE
--------------------------------------------------------

  CREATE TABLE "MOOLLS"."CHAT_USER_ROLE" 
   (	"ROLE_ID" NUMBER, 
	"ROLE_NAME" VARCHAR2(20 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CHAT_USER_STATUS
--------------------------------------------------------

  CREATE TABLE "MOOLLS"."CHAT_USER_STATUS" 
   (	"STATUS_ID" NUMBER, 
	"STATUS_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

Insert into MOOLLS.CHAT_EVENT_TYPE (EVENT_TYPE_ID,EVENT_NAME) values (1,'REGISTERED');
Insert into MOOLLS.CHAT_EVENT_TYPE (EVENT_TYPE_ID,EVENT_NAME) values (2,'MESSAGE');
Insert into MOOLLS.CHAT_EVENT_TYPE (EVENT_TYPE_ID,EVENT_NAME) values (3,'LOGOUT');
Insert into MOOLLS.CHAT_EVENT_TYPE (EVENT_TYPE_ID,EVENT_NAME) values (4,'LOGIN');
Insert into MOOLLS.CHAT_EVENT_TYPE (EVENT_TYPE_ID,EVENT_NAME) values (5,'KICKED');
Insert into MOOLLS.CHAT_EVENT_TYPE (EVENT_TYPE_ID,EVENT_NAME) values (6,'BANNED');


Insert into MOOLLS.CHAT_USER_ROLE (ROLE_ID,ROLE_NAME) values (2,'USER');
Insert into MOOLLS.CHAT_USER_ROLE (ROLE_ID,ROLE_NAME) values (3,'ADMIN');
Insert into MOOLLS.CHAT_USER_ROLE (ROLE_ID,ROLE_NAME) values (1,'ANONYMOUS');


Insert into MOOLLS.CHAT_USER_STATUS (STATUS_ID,STATUS_NAME) values (1,'ACTIVE');
Insert into MOOLLS.CHAT_USER_STATUS (STATUS_ID,STATUS_NAME) values (2,'BANNED');
Insert into MOOLLS.CHAT_USER_STATUS (STATUS_ID,STATUS_NAME) values (3,'KICKED');
--------------------------------------------------------
--  DDL for Index SYS_C006989
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOOLLS"."SYS_C006989" ON "MOOLLS"."CHAT_USER_STATUS" ("STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C006992
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOOLLS"."SYS_C006992" ON "MOOLLS"."CHAT_USER_ROLE" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C006995
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOOLLS"."SYS_C006995" ON "MOOLLS"."CHAT_EVENT_TYPE" ("EVENT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007038
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOOLLS"."SYS_C007038" ON "MOOLLS"."CHAT_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007050
--------------------------------------------------------

  CREATE UNIQUE INDEX "MOOLLS"."SYS_C007050" ON "MOOLLS"."CHAT_EVENT" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CHAT_EVENT
--------------------------------------------------------

  ALTER TABLE "MOOLLS"."CHAT_EVENT" ADD PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MOOLLS"."CHAT_EVENT" MODIFY ("EVENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "MOOLLS"."CHAT_EVENT" MODIFY ("EVENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHAT_EVENT_TYPE
--------------------------------------------------------

  ALTER TABLE "MOOLLS"."CHAT_EVENT_TYPE" ADD PRIMARY KEY ("EVENT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MOOLLS"."CHAT_EVENT_TYPE" MODIFY ("EVENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOOLLS"."CHAT_EVENT_TYPE" MODIFY ("EVENT_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHAT_USER
--------------------------------------------------------

  ALTER TABLE "MOOLLS"."CHAT_USER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MOOLLS"."CHAT_USER" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "MOOLLS"."CHAT_USER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MOOLLS"."CHAT_USER" MODIFY ("REG_TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "MOOLLS"."CHAT_USER" MODIFY ("MD5_PASS" NOT NULL ENABLE);
  ALTER TABLE "MOOLLS"."CHAT_USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOOLLS"."CHAT_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHAT_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "MOOLLS"."CHAT_USER_ROLE" ADD PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MOOLLS"."CHAT_USER_ROLE" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOOLLS"."CHAT_USER_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHAT_USER_STATUS
--------------------------------------------------------

  ALTER TABLE "MOOLLS"."CHAT_USER_STATUS" ADD PRIMARY KEY ("STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MOOLLS"."CHAT_USER_STATUS" MODIFY ("STATUS_NAME" NOT NULL ENABLE);
  ALTER TABLE "MOOLLS"."CHAT_USER_STATUS" MODIFY ("STATUS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CHAT_EVENT
--------------------------------------------------------

  ALTER TABLE "MOOLLS"."CHAT_EVENT" ADD CONSTRAINT "CHAT_EVENT_CHAT_EVENT_TYPE_FK" FOREIGN KEY ("EVENT_TYPE")
	  REFERENCES "MOOLLS"."CHAT_EVENT_TYPE" ("EVENT_TYPE_ID") ENABLE;
  ALTER TABLE "MOOLLS"."CHAT_EVENT" ADD CONSTRAINT "CHAT_EVENT_FROM_USER__FK" FOREIGN KEY ("FROM_USER")
	  REFERENCES "MOOLLS"."CHAT_USER" ("USER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MOOLLS"."CHAT_EVENT" ADD CONSTRAINT "CHAT_EVENT_TO_USER__FK" FOREIGN KEY ("TO_USER")
	  REFERENCES "MOOLLS"."CHAT_USER" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHAT_USER
--------------------------------------------------------

  ALTER TABLE "MOOLLS"."CHAT_USER" ADD CONSTRAINT "CHAT_USER_CHAT_USER_STATUS_FK" FOREIGN KEY ("STATUS")
	  REFERENCES "MOOLLS"."CHAT_USER_STATUS" ("STATUS_ID") ENABLE;
  ALTER TABLE "MOOLLS"."CHAT_USER" ADD CONSTRAINT "CHAT_USER_USER_ROLE_FK" FOREIGN KEY ("ROLE")
	  REFERENCES "MOOLLS"."CHAT_USER_ROLE" ("ROLE_ID") ENABLE;
